

CREATE TABLE Shooters(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(55) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE RPG(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE Racing(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE Sports(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE SurvivalHorror(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE Mobile(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE HonorableMentions(
gameID INT PRIMARY KEY IDENTITY (1,1),
Title VARCHAR(25) NOT NULL,
Genre VARCHAR(25) NOT NULL,
Rating INT NOT NULL,
gamePlatformID INT NOT NULL,
);


CREATE TABLE platforms(
platformID INT PRIMARY KEY IDENTITY (1,1),
platformName VARCHAR(25)
);